/**
 * NEXLINE System Constants & Configurations
 */

const QUEUE_WEIGHTS = {
  EMERGENCY: 100,
  VIP: 70,
  ELDERLY: 50,
  APPOINTMENT: 20,
  WALK_IN: 10,
  WAIT_TIME_MULTIPLIER: 1.5,
  AGE_BONUS: 20,
  AUTO_ESCALATION_THRESHOLD_MINS: 30,
};

const TOKEN_STATUS = {
  WAITING: 'WAITING',
  IN_CONSULTATION: 'IN_CONSULTATION',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  CANCELLED: 'CANCELLED',
  EXPIRED: 'EXPIRED',
};

const TOKEN_TYPE = {
  WALK_IN: 'WALK_IN',
  APPOINTMENT: 'APPOINTMENT',
  EMERGENCY: 'EMERGENCY',
  ELDERLY: 'ELDERLY',
  VIP: 'VIP',
};

const USER_ROLES = {
  ADMIN: 'ADMIN',
  DOCTOR: 'DOCTOR',
  RECEPTIONIST: 'RECEPTIONIST',
  PATIENT: 'PATIENT',
};

const DOCTOR_STATUS = {
  AVAILABLE: 'AVAILABLE',
  ON_BREAK: 'ON_BREAK',
  IN_CONSULTATION: 'IN_CONSULTATION',
  OFFLINE: 'OFFLINE',
};

const DEPT_PREFIXES = {
  CARDIOLOGY: 'CARD',
  NEUROLOGY: 'NEUR',
  ORTHOPEDICS: 'ORTH',
  PEDIATRICS: 'PEDI',
  EMERGENCY: 'EMG',
  GENERAL: 'OPD',
};

module.exports = {
  QUEUE_WEIGHTS,
  TOKEN_STATUS,
  TOKEN_TYPE,
  USER_ROLES,
  DOCTOR_STATUS,
  DEPT_PREFIXES,
};
